---
- name: add_hosts
  hosts: 
    - sewon-node01
    - sewon-node02
    - sewon-node03
    - sewon-node04

  tasks:
    - name: Add hosts file
      blockinfile:
          path: /etc/hosts
          block: |
             192.168.122.56 sewon-node01
             192.168.122.57 sewon-node02
             192.168.122.58 sewon-node03
             192.168.122.59 sewon-node04
