all:
  hosts:
    kube-node0[1:4]:
      ansible_user: root
      ansible_ssh_private_key_file: ~/mz_keys/mz_kisti.pem
  children:
    g_kubernetes:
      children:
        control-plain:
          hosts:
            kube-node01:
            kube-node02:
            kube-node03:
          vars:
            ansible_user: root
            ansible_ssh_private_key_file: ~/mz_keys/mz_kisti.pem
        worker:
          hosts:
            kube-node04:
          vars:
            ansible_user: root
            ansible_ssh_private_key_file: ~/mz_keys/mz_kisti.pem
